[package]
name = "picoapp"
version = "0.2.1"
edition = "2024"

[lib]
name = "picoapp"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
gpui-kit = "=0.6.6"
futures = "0.3"
image = "0.25"
log = "0.4"
pyo3 = "0.22"
rodio = "0.19.0"
smallvec = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
gpui-kit = { version = "=0.6.6", features = ["test-support"] }

[profile.dev.package."*"]
opt-level = 2
