# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# https://docs.github.com/en/actions/guides/building-and-testing-python

name: checks

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # at 00:00 every Sunday

jobs:

  checks:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"] # keep in line with xref:supported-python-versions

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Rust: Install toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: "Install prerequisites"
        run: |
          dpkg-query -l libasound2-dev || true
          dpkg-query -l libdbus-1-dev || true
          sudo apt-get update
          sudo apt install libasound2-dev libdbus-1-dev libxkbcommon-x11-dev \
            libwayland-dev libx11-xcb-dev libfontconfig-dev clang
          dpkg-query -l libasound2-dev || true
          dpkg-query -l libdbus-1-dev || true

      - name: "Rust: Check format"
        run: |
          . env.sh
          ./scripts/check_rust_format

      - name: "Rust: Check lint"
        run: |
          . env.sh
          ./scripts/check_rust_lint

      - name: "Rust: Tests"
        run: |
          . env.sh
          ./scripts/check_rust_test

      - name: "Install uv"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: "Python: Install dependencies"
        run: |
          . env.sh
          ./scripts/venv_create
          . env.sh
          ./scripts/venv_install
          uv pip freeze

      - name: "Install native package"
        run: |
          . env.sh
          ./scripts/maturin_develop

      - name: "Python: Check types"
        run: |
          . env.sh
          ./scripts/check_python_types

      - name: "Python: Check linter"
        run: |
          . env.sh
          ./scripts/check_python_lint

      - name: "Python: Check format"
        run: |
          . env.sh
          ./scripts/check_python_format

      - name: "Python: Tests"
        run: |
          . env.sh
          ./scripts/check_python_test

      - name: "Integration test (minimal dependencies)"
        run: |
          . env.sh
          ./scripts/check_integration_minimal_install

