# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# https://docs.github.com/en/actions/guides/building-and-testing-python

name: checks

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # at 00:00 every Sunday

jobs:

  tests:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Rust: Install toolchain"
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: "Rust: Tests"
        run: |
          cargo test

      - name: "Install uv"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: "Python: Install dependencies"
        run: |
          ./scripts/venv_create
          . ./venv/bin/activate
          uv pip install -r requirements_dev.in -r requirements.in
          uv pip freeze

      - name: "Install native package"
        run: |
          . ./venv/bin/activate
          maturin develop

      - name: "Python: Check types"
        run: |
          . ./venv/bin/activate
          mypy .

      - name: "Python: Check linter"
        run: |
          . ./venv/bin/activate
          flake8

      - name: "Python: Check format"
        run: |
          . ./venv/bin/activate
          black --check .
          isort --check .

      - name: "Python: Tests"
        run: |
          . ./venv/bin/activate
          pytest

